# Generated by Django 4.2.2 on 2023-10-29 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0002_alter_project_projectrating_alter_skills_skillrank'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Experience',
            new_name='EducationModel',
        ),
        migrations.RenameModel(
            old_name='Education',
            new_name='ExperienceModel',
        ),
        migrations.RenameModel(
            old_name='Information',
            new_name='InformationModel',
        ),
        migrations.RenameModel(
            old_name='Message',
            new_name='MessageModel',
        ),
        migrations.RenameModel(
            old_name='Project',
            new_name='ProjectModel',
        ),
        migrations.RenameModel(
            old_name='Skills',
            new_name='SkillsModel',
        ),
    ]
